<?php
/**
 * 行情 基类.
 * User: David
 * Date: 2019/01/24
 * Time: 17:30 PM
 */

require_once __DIR__.'/../app.php';

class app_market_base extends app {

    protected $currency;

    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
        /*做个兼容，行情基类中CNY转换成RMB*/
        $currency = trim( post( 'currency' ) );

        if ($currency == 'CNY') {
            $this->currency = 'RMB';
        } else {
            $this->currency = $currency;
        }
    }

    protected function encodeParams($params) {
        foreach ($params as $k => $param) {
            $param = $this->rsaEncodeFix($param);
            $params[$k] = $param;
        }
        return $params;
    }

    protected function rsaEncodeFix( $data ) {
        $arr = array();
        foreach ( str_split( $data, 117 ) as $d ) {
            $arr[] = $this->rsaEncode( $d );
        }
        return implode( ';', $arr );
    }

    protected function rsaEncode( $data ) {
        require_once 'core/v2.1/RSA.php';

        $publicKey = '';
        return RSA::encodeByPublicKey( $data, $publicKey );
    }



}